name: Test Sentry Source Map Upload

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      NODE_ENV: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps --include=dev

      - name: Build Electron app for Windows
        run: npm run build:electron:win --publish="never"

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: ./release/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.exe

      - name: Upload Windows Blockmap as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Blockmap
          path: ./release/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.exe.blockmap

      - name: Upload Windows latest.yml as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows latest.yml
          path: ./release/${{ env.VERSION }}/latest.yml
