name: Test Sentry Source Map Upload

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install dmg-license
        run: npm i dmg-license

      - name: Install jq
        run: brew install jq

      - name: Get name and version from package.json
        run: |
          echo "NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build Electron App for macOS
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          NODE_ENV: production
        run: npm run build:electron:mac

      - name: Upload macOS DMG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS DMG
  path: ./release/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.dmg
