name: Test Sentry Source Map Upload

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      NODE_ENV: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps --include=dev

      - name: Generate static assets
        run: npm run generate

      - name: Check for source maps
        run: find .output/ -name "*.map" || echo "No source maps found"
